Updated retrain yaml file

diff --git a/.github/workflows/retrain.yml b/.github/workflows/retrain.yml
--- a/.github/workflows/retrain.yml
+++ b/.github/workflows/retrain.yml
@@ -32,6 +32,10 @@ jobs:
         run: |
           git config user.name "github-actions"
           git config user.email "github-actions@github.com"
-          git add src/model.pkl
-          git commit -m "🔁 Retrained model - $(date +'%Y-%m-%d')" || echo "No changes to commit"
-          git push
+          if [ -f src/model.pkl ]; then
+            git add src/model.pkl
+            git commit -m "🔁 Retrained model - $(date +'%Y-%m-%d')" || echo "No changes to commit"
+            git push
+          else
+            echo "❌ src/model.pkl not found — skipping commit."
+          fi
